### DISCUSSION TITLE
How can I setup auto-formatting on save with Helix?

### DISCUSSION THREAD

**Discussion by elijahblackmore** [biomejs/biome#2263] [Q&A] [answered]
I am on Helix version 23.10, and I have installed the CLI via `brew install biome`. I have also ran `biome init` in the project directory, so I should have a valid `biome.json` file in-case that is required.

As per [these instructions](https://github.com/biomejs/biome/blob/main/editors/helix/manual.md), I have copied these lines into my `languages.toml` file:

```toml
[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "jsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "js"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true
```

Linting appears to be working correctly, but there isn't any formatting on save. I can run the command `biome format --write <file>` to format, and perhaps there is a way to integrate this command using the `formatter` key, but I haven't figured out a working solution yet.

`typescript-language-server` seems to have its own formatter, which I'm assuming is the case with Biome, and I shouldn't need to add something like `formatter = { command = "prettier", args = ["--parser", "typescript"] }` which is what I used for Prettier.

Am I doing something horribly wrong here? This is my first time using this, and I'm not well versed in configuring languages for Helix. Any pointers would be greatly appreciated!

**Comment by elijahblackmore** [comment, marked as answer]
Adding the following line solved this:
```toml
formatter = { command = "biome", args = ["format", "--stdin-file-path", "test.js"] }
```

**Comment by janos-r** [comment]
Not clear why a file name is needed, but yes, I also got it working thanks to this explanation. The docs should definitely be updated. I found this thread through an old post on the discord.

the relevant lines in my config:
```toml
[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "typescript"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path=prd.js", # no idea why a file name is needed
  "--indent-style=space",
  "--indent-width=4",
] }
```
