### DISCUSSION TITLE
Linter: support for `@custom-media`

### DISCUSSION THREAD

**Discussion by jmuzina** [biomejs/biome#4389] [Ideas]
It would be nice if Biome's correctness linter didn't flag usages of `@custom-media`. This at-rule [hasn't been implemented by browsers yet](https://caniuse.com/?search=custom-media) but it has been [specced](https://www.w3.org/TR/mediaqueries-5/#at-ruledef-custom-media). People should be able to use it with CSS tools so that they can move towards using it sooner rather than later.

I.E., consider this code:

```css
@custom-media --small-viewport (380px > width);

@media (--small-viewport) {
  * {
    color: red;
  }
}
```

This generates a linting error:
```
  ℹ Unexpected unknown media feature name.
  ℹ You should use media feature names defined in the CSS Specifications.
src/breakpoints.css:17:8 lint/correctness/noUnknownMediaFeatureName ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

Tools like [LightningCSS](https://lightningcss.dev/transpilation.html#custom-media-queries) and [PostCSS](https://www.npmjs.com/package/postcss-custom-media) can convert this code to use browser-supported media queries:
```css
@media (max-width: 379.999px) {
  * {
    color: red;
  }
}
```

Currently, my only options to get Biome to not throw errors here is to ignore the `noUnknownMediaFeatureName` rule on every usage of custom media or to disable the rule entirely.
