### DISCUSSION TITLE
useExhaustiveDependencies not working in VS Code

### DISCUSSION THREAD

**Discussion by igortas** [biomejs/biome#4588] [Q&A]
useExhaustiveDependencies rule stopped working on latest vscode and latest biome. I've tried to install also the plugin, but still the same.
Biome never checks for dependency array in well known hooks like useEffect. useMemo or useCallback.

**Comment by arendjr** [comment]
Sorry for the late response! Have you managed to get it to work?

**Comment by igortas** [comment]
@arendjr 
Still not giving any warning with latest ```1.9.4``` version, flag is set to error in ```biome.json```:

```
"useExhaustiveDependencies": "error"
```

I've tried both versions of the plugin ```release``` and ```pre-release```,  still not reporting....

Not repoting also on ```pre-commit``` or ```pre-push```:

```

pre-commit:
  commands:
    check:
      glob: '*.{ts,d.mts,tsx,json}'
      run: npx @biomejs/biome check --write --no-errors-on-unmatched --files-ignore-unknown=true {staged_files} && git update-index --again
```

I'm using ```WSL 2```
```
  System:
    OS: Linux 5.15 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
  Binaries:
    Node: 22.6.0 - ~/.nvm/versions/node/v22.6.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.6.0/bin/npm
```
