### DISCUSSION TITLE
--changed doesn't grab any files in CI

### DISCUSSION THREAD

**Discussion by Andrew-Chen-Wang** [biomejs/biome#4896] [Q&A]
This is my GitHub Action

```yml
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Check formatting with Biome
        run: biome ci --changed --no-errors-on-unmatched .
```

---

Here are some local tests

Resulting in this for a PR with 3 commits:
```
  biome ci --changed --no-errors-on-unmatched .
  shell: /usr/bin/bash -e {0}
Checked 0 files in 65µs. No fixes applied.
```
When I run locally in a PR branch:
```
biome ci --changed --no-errors-on-unmatched .
Checked 196 files in 24ms. No fixes applied.
```
Running without `--changed`

```
biome ci --no-errors-on-unmatched .
Checked 213 files in 31ms. No fixes applied.
```

Curiously, running just `check`:
```
npx @biomejs/biome check --no-errors-on-unmatched --files-ignore-unknown=true --write .
Checked 213 files in 37ms. No fixes applied
```

---

So what's going?

I think `--changed` requires the main branch to actually be set up. So we could modify the action to look like this:

```yml
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Checkout main branch
        if: github.event_name == 'pull_request'
        run: git fetch origin main --depth 1
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Check formatting with Biome
        run: biome ci --changed --no-errors-on-unmatched .
```

I wrote a fetch depth of 2 thinking that the 2 commits I have on a PR would compare with the main branch, but, unfortunately, no files were collected.

So there are two bugs in my opinion:
1. There should be some docs documenting how to lint in CI with `--changed`.
2. I feel like `--changed` is missing some files. At first I thought "oh maybe it skipped collecting new files", but that doesn't make sense since that's technically a change.

Would love to get some thoughts above:)

For now, I've resolved to not using `--changed`. When doing type checking in mypy in python land, not checking all files at the same time made us sometimes miss changes, so I worry a linter would have a similar issue due to the sheer nature of git.

Actually this is interesting: I just merged my PR and got this output in both the PR and main branch output

```
Run biome ci --no-errors-on-unmatched .
Checked 212 files in [4]
```

But locally, I got

```
biome ci --no-errors-on-unmatched .
Checked 213 files in 24ms. No fixes applied.
```
