### DISCUSSION TITLE
Helix config expanding ideas for using it withing the project and locally

### DISCUSSION THREAD

**Discussion by Emcho0** [biomejs/biome#5389] [Ideas]
# Personal issues
Whenever I use helix for formatting, it will not apply the fixes. Instead it will print the text that there are fixes instead of applying them. The lsp works fine. Would there be any chance to update the helix documentation to include settings such as default formatter and finding roots for biome.json for the settings? In another picture lsp shows issues which means it does work.

![image1](https://github.com/user-attachments/assets/70d17133-63cb-4325-b2d6-a648ad7c19a6)
![image2](https://github.com/user-attachments/assets/35906a23-28cf-4b26-9a20-968999640f3a)
![image3](https://github.com/user-attachments/assets/a2be929a-da49-4b78-a357-b5d949ab2d99)

Helix languages.toml
```toml
[language-server]
biome = { command = "npx", args = ["biome", "lsp-proxy"] }

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true
formatter = { command = "npx", args = ["biome", "check", "--write"] }

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true
formatter = { command = "npx", args = ["biome", "check", "--write"] }

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
formatter = { command = "npx", args = ["biome", "check", "--write"] }
[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
formatter = { command = "npx", args = ["biome", "check", "--write"] }

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
```
# Suggestions
I think that there should be an option in helix to watch for the biome.json config file and give more flexibilty for configuring biome tool in helix however they like.

```toml
[language-server.biome.options]
config = true
```

**Comment by Emcho0** [comment]
I want to add that for every file type the roots should be like this
So that we can avoid using formatter args for defining which is gonna be the indent width, style and so on
```toml
[language-server]
# When ran locally
# biome = { command = "npx", args = ["biome", "lsp-proxy"] }
# When ran globally
biome = {command = "biome", args = ["lsp-proxy"]}
[[language]]
name = "javascript"
roots = ["biome.json", "biome.jsonc", "package.json"]
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true


[[language]]
name = "typescript"
roots = ["biome.json", "biome.jsonc", "package.json"]
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true


[[language]]
name = "tsx"
auto-format = true
roots = ["biome.json", "biome.jsonc", "package.json"]
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "jsx"
roots = ["biome.json", "biome.jsonc", "package.json"]
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]


[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
```
