### DISCUSSION TITLE
📎 Adding `glob` to the biome cli (.js, .html, .jsx and any supported file type)

### DISCUSSION THREAD

**Discussion by Emcho0** [biomejs/biome#5457] [Ideas]
### Description

When formatting in helix for example, the formatter only works when you specify a file name like app.tsx, and then the formatting would be considered ok and normal. This is very bad practice and some file names that are not matched would not work. 

```toml
# Example snippet for configuring biome with web dev
[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "javascript"
roots = ["biome.json", "biome.jsonc", "package.json"]
language-servers = [
    { name = "typescript-language-server", except-features = ["format"] },
    "biome"
]
auto-format = true
formatter = { command = "biome", args = ["check","--write", "--stdin-file-path","*.js"] }
[[language]]
name = "typescript"
language-servers = [
    { name = "typescript-language-server", except-features = ["format"] },
    "biome"
]
auto-format = true
formatter = { command = "biome", args = ["check","--write", "--stdin-file-path","*.ts"] }


[[language]]
name = "tsx"
auto-format = true
roots = ["biome.json", "biome.jsonc", "package.json"]
language-servers = [
    { name = "typescript-language-server", except-features = ["format"] },
    "biome"
]
formatter = { command = "biome", args = ["check","--write", "--stdin-file-path","*.tsx"] }

[[language]]
name = "jsx"
roots = ["biome.json", "biome.jsonc", "package.json"]
auto-format = true
language-servers = [
    { name = "typescript-language-server", except-features = ["format"] },
    "biome"
]
formatter = { command = "biome", args = ["check","--write", "--stdin-file-path","*.jsx"] }

# Add more langs like html and others when biome 2.0 releases

```

This way when formatting, it should match the file extension and nothing else. It would make formatting and linting in helix way easier and wouldn't hurt the performance of the formatter.
