### DISCUSSION TITLE
CSS lint rule to restrict the use of `outline: none;` on focus

### DISCUSSION THREAD

**Discussion by mehm8128** [biomejs/biome#6182] [Rule suggestion]
[stylelint-a11y](https://github.com/YozhikM/stylelint-a11y) has `no-outline-none` rule that disallow users to use `outline: none;` on focus.
We should always show outline when users focus the element with their keyboard especially for users who use only keyboard to manipulate PC because they love to use keyboard over mouse, or if they are limited to use their arms or hands for some reasons.
Such people recognize what element they are focusing and based on that they will decide which key they will press next. So we shouldn't set `outline: none;` on focus (or instead of that we should set `border` as alternative).

For example, invalid and valid CSS for this rule is the following (I brought sample code from stylelint-a11y/no-outline-none).

**invalid**
```css
.foo:focus {
  outline: 0;
}

.bar:focus {
  outline: none;
}

.baz:focus {
  outline: none;
  border: transparent;
}

.quux {
  .quuux:focus {
    outline: 0;
  }
}
```

**valid**
```css
.foo {
  outline: 0;
}

$primary-color: #333;
.bar:focus {
  outline: 1px solid $primary-color;
}

.baz:focus {
  outline: 1px solid #333;
}

.quux:focus {
  outline: 0;
  border: 1px solid #000;
}
```

refs
[stylelint-a11y/no-outline-none](https://github.com/YozhikM/stylelint-a11y/blob/master/src/rules/no-outline-none/README.md)
[outline - MDN #Accessibility](https://developer.mozilla.org/en-US/docs/Web/CSS/outline#accessibility)
[How To Design Useful and Usable Focus Indicators - deque](https://www.deque.com/blog/give-site-focus-tips-designing-usable-focus-indicators/)
[Understanding Success Criterion 2.4.7: Focus Visible | WAI | W3C](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html)
[F78: Failure of Success Criterion 1.4.11 and 2.4.7 due to styling element outlines and borders in a way that removes or renders non-visible the visual focus indicator | WAI | W3C](https://www.w3.org/WAI/WCAG21/Techniques/failures/F78)
