### DISCUSSION TITLE
Aborting on write during pre-commit?

### DISCUSSION THREAD

**Discussion by jceipek** [biomejs/biome#6285] [Q&A]
My team likes to auto-lint + format code during pre-commit but wants to manually approve any automatic changes before they make it into commits (we don't want to commit code that doesn't pass linting/formatting, and we also don't want to commit code before seeing it). I'm trying to figure out if there's a good way to set up this kind of workflow with Biome. I read through the docs and couldn't find anything relevant, but perhaps I missed something?

# Use Case Description

1. I make changes to files A, B, and C.
2. I stage my changes to file A and part of my changes to file B. The changes I made wouldn't pass `biome check` if I were to run it.
3. I make a commit. My git hooks temporarily stash the unstaged changes to files B and C and run `biome check --write` on the staged files. Because `biome check` found formatting issues, I want the automatic changes to show up as unstaged changes.
4. I look through the automatic suggestions and stage the ones that make sense. I discover that one of the automatic changes doesn't make sense (perhaps it's something I need to manually ignore via https://biomejs.dev/formatter/#ignore-code or perhaps I need to disable a rule via https://biomejs.dev/linter/#configuration), so I discard that change and manually modify the code/the configuration.
5. When everything looks good, I retry making the commit.

# Workaround

My current `lefthook.yml` is:

```
pre-commit:
  commands:
    check-biome:
      glob: "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx,json,jsonc}"
      run: npx @biomejs/biome check --write --no-errors-on-unmatched --files-ignore-unknown=true --colors=off {staged_files} | grep -q "No fixes"
```

While this works for now, I'd prefer not to rely on the specific text output of CLI commands since it might change in future versions. An alternative would be to modify the `pre-commit` hook to run `biome check {staged_files} || (biome check --write {staged_files} && exit 1)` but that's more complicated and takes longer to run.

Is there a better way?
