### ISSUE TITLE
🐛 CSS parsing issues

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#2789]
### Environment information

```block
main
```

### What happened?

The following snippets fire parsing errors, while they should not. Taken from [`full.css`](https://cdn.jsdelivr.net/npm/daisyui@3.9.2/dist/full.css).

[Link](https://biomejs.dev/playground/?files.main.css=LgBjAGgAYQB0AC0AaQBtAGEAZwBlACAAewAKACAAIAAgACAAZwByAGkAZAAtAHIAbwB3ADoAIABzAHAAYQBuACAAMgAgAC8AIABzAHAAYQBuACAAMgA7AAoAIAAgACAAIABhAGwAaQBnAG4ALQBzAGUAbABmADoAIABmAGwAZQB4AC0AZQBuAGQACgB9AA%3D%3D)
```css
.chat-image {
    grid-row: span 2 / span 2;
    align-self: flex-end
}
```

[Link](https://biomejs.dev/playground/?files.main.css=LgBjAGwAYQBzAHMAIAB7AAoACQB0AGUAeAB0AC0AcwBoAGEAZABvAHcAOgAgADAAIAAxAHAAeAAgAHIAZwBiACgAMAAgADAAIAAwACAALwAgAHYAYQByACgALQAtAGcAbABhAHMAcwAtAHQAZQB4AHQALQBzAGgAYQBkAG8AdwAtAG8AcABhAGMAaQB0AHkALAAgADUAJQApACkACgB9AA%3D%3D)
```css
.class {
	text-shadow: 0 1px rgb(0 0 0 / var(--glass-text-shadow-opacity, 5%))
}
```

[Link](https://biomejs.dev/playground/?files.main.css=LgBjAGwAYQBzAHMAIAB7AAoAIAAgAGIAbwB4AC0AcwBoAGEAZABvAHcAOgAgADAAIAAwACAAMAAgADEAcAB4ACAAcgBnAGIAKAAyADUANQAgADIANQA1ACAAMgA1ADUAIAAvACAAdgBhAHIAKAAtAC0AZwBsAGEAcwBzAC0AYgBvAHIAZABlAHIALQBvAHAAYQBjAGkAdAB5ACwAIAAxADAAJQApACkAIABpAG4AcwBlAHQALAAKACAAIAAgACAAIAAgADAAIAAwACAAMAAgADIAcAB4ACAAcgBnAGIAKAAwACAAMAAgADAAIAAvACAANQAlACkACgB9AA%3D%3D)
```css
.class {
  box-shadow: 0 0 0 1px rgb(255 255 255 / var(--glass-border-opacity, 10%)) inset,
      0 0 0 2px rgb(0 0 0 / 5%)
}
```

Others are more or less the same.

### Expected result

They should not emit parsing errors, I suppose

cc @denbezrukov 

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
[Link](https://biomejs.dev/playground/?files.main.css=LgBmAGkAbABlAC0AZgBpAGUAbABkACAAaQBuAHAAdQB0AFsAdAB5AHAAZQA9AGYAaQBsAGUAXQAgAHsACgAgACAAZgBpAGwAdABlAHIAOgAgAGEAbABwAGgAYQAoAG8AcABhAGMAaQB0AHkAPQAwACkAOwAKAH0A).

From [`materialize.css`](https://raw.githubusercontent.com/Dogfalo/materialize/v1-dev/dist/css/materialize.css)

```css
.file-field input[type=file] {
  filter: alpha(opacity=0);
}
```

Is `=0` valid?

**Comment by ematipico** [comment]
[Link](https://biomejs.dev/playground/?files.main.css=LgB1AGkALgBhAHQAdABhAGMAaABlAGQALgBzAHQAZQBwAHMAIAB7AAoAIAAgAHcAaQBkAHQAaAA6ACAAYwBhAGwAYwAoADEAMAAwACUAIAArACAAKAAtAC0AMQBwAHgAIAAqACAAMgApACkAIAAhAGkAbQBwAG8AcgB0AGEAbgB0ADsACgAgACAAbQBhAHIAZwBpAG4AOgAgADAAZQBtACAALQAxAHAAeAAgADAAOwAKACAAIABtAGEAeAAtAHcAaQBkAHQAaAA6ACAAYwBhAGwAYwAoADEAMAAwACUAIAArACAAKAAtAC0AMQBwAHgAIAAqACAAMgApACkAOwAKACAAIABiAG8AcgBkAGUAcgAtAHIAYQBkAGkAdQBzADoAIAAwAC4AMgA4ADUANwAxADQAMgA5AHIAZQBtACAAMAAuADIAOAA1ADcAMQA0ADIAOQByAGUAbQAgADAAZQBtACAAMABlAG0AOwAKAH0A)

From [`semantic.css`](https://raw.githubusercontent.com/Semantic-Org/Semantic-UI/master/dist/semantic.css)

```css
.ui.attached.steps {
  width: calc(100% + (--1px * 2)) !important;
  margin: 0em -1px 0;
  max-width: calc(100% + (--1px * 2));
  border-radius: 0.28571429rem 0.28571429rem 0em 0em;
}
```

It seems that `--1px` [is valid](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.ui.attached.steps%20%7B%5Cn%20%20width%3A%20calc(100%25%20%2B%20(--1px%20*%202))%20!important%3B%5Cn%20%20margin%3A%200em%20-1px%200%3B%5Cn%20%20max-width%3A%20calc(100%25%20%2B%20(--1px%20*%202))%3B%5Cn%20%20border-radius%3A%200.28571429rem%200.28571429rem%200em%200em%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)
