### ISSUE TITLE
🐛 error access vscode extensions

### ISSUE THREAD

**Issue by wcastand** [biomejs/biome#293]
### Environment information

```block
biome rage return :


Rage discovered this running server using an incompatible version of Biome.

Server:
  Version:                      1.1.2
```

yarn v3 on a monorepo.
```


### What happened?

update vscode extension got an error:

```
Biome client: couldn't create connection to server.

/node_modules/.bin/biome: Permission denied
```
discord asked me to run this command and it fixed the issue:

`chmod +x ./node_modules/.bin/biome`

been asked to reference this issue: https://github.com/rome/tools/pull/3800

### Expected result

update the vscode extension and it works

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by nhedger** [comment]
Could you provide a repository that reproduces this issue? This would help a lot.

**Comment by wcastand** [comment]
sorry but at work so not really the time, plus not idea why it happened so can't really reproduce. i just update my vscode extensions :/

**Comment by Conaclos** [comment]
Which OS do you use?

**Comment by Vivalldi** [comment]
Same thing here. It's failing on macOS for me

**Comment by Conaclos** [comment]
I have no issue with npm on linux. Maybe a yarn-specific issue?

**Comment by nhedger** [comment]
I just tested with Yarn 3 on macOS with Biome 1.2.0 and had no issues.

**Comment by wcastand** [comment]
my yarn rage is kind of a nightmare 
https://gist.github.com/wcastand/dd2e74cdd59d350243cd8a444a1aa517

**Comment by nhedger** [comment]
Could you please:

1. Delete your `node_modules` folder
2. Reinstall your modules by running `yarn`
3. Run the following command `ls -la node_modules/.bin/biome` and paste the output here

**Comment by Vivalldi** [comment]
I've been able to reproduce by doing the following

1. Delete `node_modules`
2. Install biome vscode extension `1.2.2`
3. Install biome at `1.1.2`
4. Open a ts file to trigger biome extension

Perform double update
1. Install biome @ `1.2.0`
2. Install latest biome vscode extension
3. Reload vscode window
4. Get `Biome client: couldn't create connection to server.` error


Output of `ls -la`
```
lrwxr-xr-x  1 cosgrove  staff  27 Sep 15 12:36 node_modules/.bin/biome -> ../@biomejs/biome/bin/biome
```

Rage
```
CLI:
  Version:                      1.2.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.14.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/3.6.1"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 true

Workspace:
  Open Documents:               0

Discovering running Biome servers...

Running Biome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i The client isn't connected to any server but rage discovered this running Biome server.

Server:
  Version:                      1.2.0
  Name:                         biome_lsp
  CPU Architecture:             aarch64
  OS:                           macos

Workspace:
  Open Documents:               0

Other Active Server Workspaces:

Workspace:
  Open Documents:               0
  Client Name:                  Visual Studio Code
  Client Version:               1.82.2

Biome Server Log:

! Please review the content of the log file before sharing it publicly as it may contain sensitive information:
  * Path names that may reveal your name, a project name, or the name of your employer.
  * Source code

###### last few lines below #####
├─2041630ms ERROR tower_lsp::transport failed to encode message: failed to encode response: Socket is not connected (os error 57)
├─┐biome_lsp::server::initialize{capabilities=ClientCapabilities { workspace: None, text_document: None, window: None, general: None, experimental: None }, client_info=ClientInfo { name: "biome_service", version: Some("1.2.0") }}
│ ├─0ms INFO biome_lsp::server Starting Biome Language Server...
├─┘
├─┐biome_lsp::server::biome/rage{params=RageParams}
├─┘
├─2046625ms ERROR tower_lsp::transport failed to encode message: failed to encode response: Socket is not connected (os error 57)

Incompatible Biome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i Rage discovered this running server using an incompatible version of Biome.

Server:
  Version:                      1.1.0

Incompatible Biome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i Rage discovered this running server using an incompatible version of Biome.

Server:
  Version:                      1.1.2


```

**Comment by probablyup** [comment]
This just popped up after upgrading to 1.2

```
Error - 12:51:43 PM] Biome client: couldn't create connection to server.
Error: Command "/Users/esj/code/frontend-v2/node_modules/.bin/biome __print_socket" exited with code 126
Output:
/bin/sh: /Users/esj/code/frontend-v2/node_modules/.bin/biome: Permission denied

	at getSocket (/Users/esj/.vscode/extensions/biomejs.biome-1.4.0-darwin-arm64/out/main.js:19600:11)
```

```
ℹ Rage discovered this running server using an incompatible version of Biome.

Server:
  Version:                      1.1.2
```

yarn.lock
```
"@biomejs/biome@npm:^1.2.0":
  version: 1.2.0
  resolution: "@biomejs/biome@npm:1.2.0"
  dependencies:
    "@biomejs/cli-darwin-arm64": 1.2.0
    "@biomejs/cli-darwin-x64": 1.2.0
    "@biomejs/cli-linux-arm64": 1.2.0
    "@biomejs/cli-linux-x64": 1.2.0
    "@biomejs/cli-win32-arm64": 1.2.0
    "@biomejs/cli-win32-x64": 1.2.0
  dependenciesMeta:
    "@biomejs/cli-darwin-arm64":
      optional: true
    "@biomejs/cli-darwin-x64":
      optional: true
    "@biomejs/cli-linux-arm64":
      optional: true
    "@biomejs/cli-linux-x64":
      optional: true
    "@biomejs/cli-win32-arm64":
      optional: true
    "@biomejs/cli-win32-x64":
      optional: true
  bin:
    biome: bin/biome
  checksum: 952f9faa1e8b814807829e0e46b8fe77382abf5d73659c8825c28971367ce062f75ffec66dcdd75aa706cdd01abc146b013d665a69373bab961ca33e6df327d2
  languageName: node
  linkType: hard

"@biomejs/cli-darwin-arm64@npm:1.2.0":
  version: 1.2.0
  resolution: "@biomejs/cli-darwin-arm64@npm:1.2.0"
  conditions: os=darwin & cpu=arm64
  languageName: node
  linkType: hard

"@biomejs/cli-darwin-x64@npm:1.2.0":
  version: 1.2.0
  resolution: "@biomejs/cli-darwin-x64@npm:1.2.0"
  conditions: os=darwin & cpu=x64
  languageName: node
  linkType: hard

"@biomejs/cli-linux-arm64@npm:1.2.0":
  version: 1.2.0
  resolution: "@biomejs/cli-linux-arm64@npm:1.2.0"
  conditions: os=linux & cpu=arm64
  languageName: node
  linkType: hard

"@biomejs/cli-linux-x64@npm:1.2.0":
  version: 1.2.0
  resolution: "@biomejs/cli-linux-x64@npm:1.2.0"
  conditions: os=linux & cpu=x64
  languageName: node
  linkType: hard

"@biomejs/cli-win32-arm64@npm:1.2.0":
  version: 1.2.0
  resolution: "@biomejs/cli-win32-arm64@npm:1.2.0"
  conditions: os=win32 & cpu=arm64
  languageName: node
  linkType: hard

"@biomejs/cli-win32-x64@npm:1.2.0":
  version: 1.2.0
  resolution: "@biomejs/cli-win32-x64@npm:1.2.0"
  conditions: os=win32 & cpu=x64
  languageName: node
  linkType: hard
```

How could an old version be hanging around after upgrade?
