### ISSUE TITLE
🐛 CSS parser errors: Stuck at '<=' and Stuck at '500'

### ISSUE THREAD

**Issue by ktdd** [biomejs/biome#3432]
### Environment information

```block
CLI:
  Version:                      1.8.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           unset
  JS_RUNTIME_NAME:              unset
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

When editing a css file, Biome crashes constantly with one of two errors:

```
| Source Location: D:\a\biome\biome\crates\biome_parser\src\lib.rs:535:9
| Thread Name: tokio-runtime-worker
| Message: The parser is no longer progressing. Stuck at '500' CSS_DIMENSION_VALUE:4860..4863
```
or
```
| Source Location: D:\a\biome\biome\crates\biome_parser\src\lib.rs:535:9
| Thread Name: tokio-runtime-worker
| Message: The parser is no longer progressing. Stuck at '<=' LTEQ:4859..4861
```

Offending (although invalid) CSS rules:
```css
@media only screen and width <= 500px {
    .left-block {
        width: 100%;
    }
}

@media only screen and (width 500px) {
    .left-block {
        width: 100%;
    }
}

@media only screen and (width => 500px) {
    .left-block {
        width: 100%;
    }
}
```

https://biomejs.dev/playground/?lintRules=all&files.main.css=QABtAGUAZABpAGEAIABvAG4AbAB5ACAAcwBjAHIAZQBlAG4AIABhAG4AZAAgAHcAaQBkAHQAaAAgADwAPQAgADUAMAAwAHAAeAAgAHsACgAgACAAIAAgAC4AbABlAGYAdAAtAGIAbABvAGMAawAgAHsACgAgACAAIAAgACAAIAAgACAAdwBpAGQAdABoADoAIAAxADAAMAAlADsACgAgACAAIAAgAH0ACgB9AA%3D%3D
### Expected result

It should not crash.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct
