### ISSUE TITLE
🐛 biome format issues with `cr` on windows

### ISSUE THREAD

**Issue by sibouras** [biomejs/biome#4789]
### Environment information

```block
CLI:
  Version:                      1.9.4
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           unset
  JS_RUNTIME_NAME:              unset
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

this is a copy of an issue i opened in helix

### Summary

when copying multiline text on windows and then replacing the selection with `space+R` the carriage return `cr` doesn't get removed which causes bugs in biome formatting, pasting with `space+p` which trims `cr` works fine though
### Reproduction Steps

sample code to copy

```js
const people = [
	{ name: "one", year: 2000 },
	{ name: "two", year: 2001 },
	{ name: "three", year: 2002 },
	{ name: "four", year: 2003 },
];
```

https://github.com/user-attachments/assets/9b1ba19d-3975-49db-9c68-19286e88943a

I tried this:

1. open helix, paste the sample text and save
2. `biome format` , no `cr` is showing(expected)
3. replace the selection with `space+R`
4. `biome format` shows `cr`
5. run `fmt` multiple times and biome gets confused

this is my config

```toml
[[language]]
name = "javascript"
language-servers = [
  { name = 'biome' },
  { name = 'typescript-language-server', except-features = ['format'] },
]

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]
required-root-patterns = ["biome.json", "biome.jsonc"]
```

### Expected result

expected format to handle `cr`

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct
