### ISSUE TITLE
🐛 biome-ignore-start/end doesn't work in CSS

### ISSUE THREAD

**Issue by k-utsumi** [biomejs/biome#6513]
### Environment information

```block
CLI:
  Version:                      2.0.5
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v22.16.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         npm/10.9.2

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  false

Workspace:
  Open Documents:               0
```

### What happened?

The lines after the first one are not affected in CSS.

- [playground result](https://biomejs.dev/playground/?code=LwAqACAAYgBpAG8AbQBlAC0AaQBnAG4AbwByAGUALQBzAHQAYQByAHQAIABmAG8AcgBtAGEAdAA6ACAAeAB4AHgAIAAqAC8ACgAuAGMAbwBsAC0AMQAsAAoALgBjAG8AbAAtADIALAAKAC4AYwBvAGwALQAzACwACgAuAGMAbwBsAC0ANAAsAAoALgBjAG8AbAAtADUALAAKAC4AYwBvAGwALQA2ACwACgAuAGMAbwBsAC0ANwAsAAoALgBjAG8AbAAtADgALAAKAC4AYwBvAGwALQA5ACwACgAuAGMAbwBsAC0AMQAwACwACgAuAGMAbwBsAC0AMQAxACwACgAuAGMAbwBsAC0AMQAyACAAewAgAHcAaQBkAHQAaAA6ACAAOQA2ACUAIAB9AAoALgBjAG8AbAAtADEALQBzAG0AIAB7ACAAdwBpAGQAdABoADoAIAA0AC4AMwAzACUAIAB9AAoALgBjAG8AbAAtADIALQBzAG0AIAB7ACAAdwBpAGQAdABoADoAIAAxADIALgA2ADYAJQAgAH0ACgAuAGMAbwBsAC0AMwAtAHMAbQAgAHsAIAB3AGkAZAB0AGgAOgAgADIAMQAlACAAfQAKAC4AYwBvAGwALQA0AC0AcwBtACAAewAgAHcAaQBkAHQAaAA6ACAAMgA5AC4AMwAzACUAIAB9AAoALwAqACAAYgBpAG8AbQBlAC0AaQBnAG4AbwByAGUALQBlAG4AZAAgAGYAbwByAG0AYQB0ADoAIAB4AHgAeAAgACoALwAKAC8AKgAgAGIAaQBvAG0AZQAtAGkAZwBuAG8AcgBlAC0AcwB0AGEAcgB0ACAAZgBvAHIAbQBhAHQAOgAgAHgAeAB4ACAAKgAvAAoALgBjAG8AbAAtADUALQBzAG0AIAB7ACAAdwBpAGQAdABoADoAIAAzADcALgA2ADYAJQAgAH0ACgAuAGMAbwBsAC0ANgAtAHMAbQAgAHsAIAB3AGkAZAB0AGgAOgAgADQANgAlACAAfQAKAC4AYwBvAGwALQA3AC0AcwBtACAAewAgAHcAaQBkAHQAaAA6ACAANQA0AC4AMwAzACUAIAB9AAoALgBjAG8AbAAtADgALQBzAG0AIAB7ACAAdwBpAGQAdABoADoAIAA2ADIALgA2ADYAJQAgAH0ACgAuAGMAbwBsAC0AOQAtAHMAbQAgAHsAIAB3AGkAZAB0AGgAOgAgADcAMQAlACAAfQAKAC8AKgAgAGIAaQBvAG0AZQAtAGkAZwBuAG8AcgBlAC0AcwB0AGEAcgB0ACAAZgBvAHIAbQBhAHQAOgAgAHgAeAB4ACAAKgAvAAoALgBjAG8AbAAtADEAMAAtAHMAbQAgAHsAIAB3AGkAZAB0AGgAOgAgADcAOQAuADMAMwAlACAAfQAKAC4AYwBvAGwALQAxADEALQBzAG0AIAB7ACAAdwBpAGQAdABoADoAIAA4ADcALgA2ADYAJQAgAH0ACgAuAGMAbwBsAC0AMQAyAC0AcwBtACAAewAgAHcAaQBkAHQAaAA6ACAAOQA2ACUAIAB9AAoALwAqACAAYgBpAG8AbQBlAC0AaQBnAG4AbwByAGUALQBlAG4AZAAgAGYAbwByAG0AYQB0ADoAIAB4AHgAeAAgACoALwA%3D&language=css)

```css
/* biome-ignore-start format: xxx */
.col-10-sm { width: 79.33% }
.col-11-sm {
	width: 87.66%;
}
.col-12-sm { width: 96% }
/* biome-ignore-end format: xxx */
```

### Expected result

```css
/* biome-ignore-start format: xxx */
.col-10-sm { width: 79.33% }
.col-11-sm { width: 87.66% }
.col-12-sm { width: 96% }
/* biome-ignore-end format: xxx */
```

<details>
<summary>Full code</summary>

```css
/* biome-ignore-start format: xxx */
.col-1,
.col-2,
.col-3,
.col-4,
.col-5,
.col-6,
.col-7,
.col-8,
.col-9,
.col-10,
.col-11,
.col-12 { width: 96% }
.col-1-sm { width: 4.33% }
.col-2-sm { width: 12.66% }
.col-3-sm { width: 21% }
.col-4-sm { width: 29.33% }
.col-5-sm { width: 37.66% }
.col-6-sm { width: 46% }
.col-7-sm { width: 54.33% }
.col-8-sm { width: 62.66% }
.col-9-sm { width: 71% }
.col-10-sm { width: 79.33% }
.col-11-sm { width: 87.66% }
.col-12-sm { width: 96% }
/* biome-ignore-end format: xxx */
```

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct
